apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sip93pgo8-python 
  janus-idp.io/tekton: sip93pgo8-python
  backstage.io/kubernetes-id: sip93pgo8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sip93pgo8-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml