apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sip93pgo8-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sip93pgo8-python 
  name: sip93pgo8-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sip93pgo8-python 
